import unittest
import src.game.board as board
import src.game.spaces as spcs


class TestGrasshopper(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.game_board = board.HiveGameBoard()

        cls.game_board.perform_action_helper(cls.game_board.PLACE_PIECE, (0, 0), piece_type=spcs.Piece.GRASSHOPPER)
        cls.game_board.perform_action_helper(cls.game_board.PLACE_PIECE, (1, 0), piece_type=spcs.Piece.GRASSHOPPER)
        cls.game_board.perform_action_helper(cls.game_board.PLACE_PIECE, (-1, 0), piece_type=spcs.Piece.QUEEN_BEE)

        cls.game_board.place_piece(spcs.Piece.QUEEN_BEE, (2, 1))
        cls.game_board.move_piece((-1, 0), (-1, -1))
        cls.game_board.move_piece((2, 1), (1, 1))
        cls.game_board.move_piece((-1, -1), (-1, 0))

        cls.game_board.print_board()

    def test_1_moveset_1(self):
        # Testing grasshopper as (0, 0)
        expected_moves = {(-2, 0), (2, 0), (2, 2)}
        actual_moves = self.game_board.pieces[(0, 0)].possible_moves
        self.assertEqual(expected_moves, actual_moves)

    def test_1_moveset_2(self):
        # Testing grasshopper at (1, 0)
        expected_moves = {(-2, 0), (1, 2)}
        actual_moves = self.game_board.pieces[(1, 0)].possible_moves
        self.assertEqual(expected_moves, actual_moves)

    def test_2_movement_and_movesets(self):
        self.game_board.perform_action_helper(self.game_board.MOVE_PIECE, (1, 0), new_location=(-2, 0))

        self.game_board.print_board()

        expected_moves_0_0 = {(-3, 0), (2, 2)}
        actual_moves_0_0 = self.game_board.pieces[(0, 0)].possible_moves
        self.assertEqual(expected_moves_0_0, actual_moves_0_0)

        expected_moves_negative_2_0 = {(1, 0)}
        actual_moves_negative_2_0 = self.game_board.pieces[(-2, 0)].possible_moves
        self.assertEqual(expected_moves_negative_2_0, actual_moves_negative_2_0)


class TestGrasshopperErrorsFromRandomBoards(unittest.TestCase):
    """
    This class tests errors found from running random games.
    The test cases pass if no errors occur.
    """

    @staticmethod
    def _test_game_helper(actions):
        game_board = board.BoardManager(new_manager=True)
        for action in actions[:-1]:
            game_board.perform_action(action)
        game_board.get_board().print_board()

        print(f'Perfoming final action: {actions[-1]}:')
        game_board.perform_action(actions[-1])
        game_board.get_board().print_board()

    def test_game_one(self):
        actions = [
            ('Place Piece', (0, 0), 'Spider'),
            ('Place Piece', (-1, 0), 'Ant'),
            ('Place Piece', (1, 1), 'Spider'),
            ('Place Piece', (-2, 0), 'Beetle'),
            ('Place Piece', (2, 1), 'Ant'),
            ('Place Piece', (-1, 1), 'Ant'),
            ('Place Piece', (1, 2), 'Queen Bee'),
            ('Place Piece', (-3, 0), 'Queen Bee'),
            ('Move Piece', (2, 1), (-1, -1)),
            ('Place Piece', (-4, 0), 'Beetle'),
            ('Place Piece', (-2, -2), 'Ant'),
            ('Move Piece', (-1, 1), (2, 2)),
            ('Move Piece', (-2, -2), (1, 0)),
            ('Move Piece', (2, 2), (-1, -2)),
            ('Move Piece', (1, 0), (2, 1)),
            ('Place Piece', (-1, 1), 'Grasshopper'),
            ('Move Piece', (2, 1), (2, 2)),
            ('Place Piece', (-2, -3), 'Spider'),
            ('Place Piece', (2, 1), 'Beetle'),
            ('Place Piece', (-4, -1), 'Ant'),
            ('Move Piece', (2, 2), (1, 3)),
            ('Place Piece', (-3, -3), 'Grasshopper'),
            ('Move Piece', (1, 3), (-4, -4)),
            ('Place Piece', (-1, -3), 'Spider'),
            ('Place Piece', (3, 1), 'Ant'),
            ('Move Piece', (-1, 1), (-1, -4)),
            ('Move Piece', (-4, -4), (-2, -2)),
            ('Place Piece', (0, -4), 'Grasshopper'),
            ('Move Piece', (3, 1), (0, -5)),
            ('Move Piece', (-1, -2), (1, -4)),
            ('Place Piece', (0, -6), 'Beetle'),
            ('Move Piece', (-4, -1), (0, -2)),
            ('Place Piece', (1, 0), 'Grasshopper'),
            ('Move Piece', (1, -4), (1, -3)),
            ('Place Piece', (2, 3), 'Grasshopper'),
            ('Move Piece', (0, -2), (0, -7)),
            ('Place Piece', (-1, -6), 'Grasshopper'),
            ('Move Piece', (0, -7), (-1, 1)),
            ('Move Piece', (2, 1), (2, 0)),
            ('Move Piece', (-1, 1), (-2, -4)),
            ('Move Piece', (0, -6), (-1, -6)),
            ('Move Piece', (1, -3), (-1, -7)),
            ('Move Piece', (-1, -6), (-2, -7)),
            ('Move Piece', (-2, -4), (-1, 1)),
            ('Move Piece', (-2, -7), (-1, -7)),
            ('Move Piece', (-1, 1), (-3, -4)),
            ('Move Piece', (2, 0), (1, -1)),
            ('Move Piece', (-3, -4), (1, -4)),
            ('Move Piece', (2, 3), (0, 1)),
            ('Move Piece', (1, -4), (0, -1)),
            ('Move Piece', (0, 1), (2, 1)),
            ('Move Piece', (0, -1), (-3, -4)),
            ('Move Piece', (1, 2), (0, 1)),
            ('Move Piece', (-3, -4), (-2, -1)),
            ('Move Piece', (-1, -1), (3, 2)),
            ('Move Piece', (-3, -3), (-1, -1)),
            ('Move Piece', (3, 2), (-5, 0)),
            ('Move Piece', (-2, -1), (0, -7)),
            ('Move Piece', (-5, 0), (-1, -2)),
            ('Move Piece', (0, -7), (-3, -1)),
            ('Move Piece', (-2, -2), (-5, 0)),
            ('Move Piece', (-3, -1), (2, 2)),
            ('Move Piece', (-5, 0), (-2, -6)),
            ('Move Piece', (2, 2), (-3, -6)),
            ('Move Piece', (0, 1), (-1, 1)),
            ('Move Piece', (-3, -6), (-2, -7)),
            ('Move Piece', (-2, -6), (1, -2)),
            ('Move Piece', (-2, -7), (3, 1)),
            ('Move Piece', (1, -2), (-4, -1)),
            ('Move Piece', (3, 1), (1, -3)),
            ('Move Piece', (-4, -1), (-3, -4)),
            ('Move Piece', (1, -3), (0, 2)),
            ('Move Piece', (-3, -4), (-2, -2)),
            ('Move Piece', (0, 2), (3, 2)),
            ('Move Piece', (-1, -2), (-5, -1)),
            ('Move Piece', (3, 2), (0, -7)),
            ('Move Piece', (1, -1), (2, 0)),
            ('Move Piece', (0, -7), (0, -1)),
            ('Move Piece', (-5, -1), (1, -3)),
            ('Move Piece', (0, -1), (-1, -8)),
            ('Move Piece', (1, 0), (-5, 0)),
            ('Move Piece', (-1, -8), (-1, -2)),
            ('Move Piece', (-5, 0), (1, 0)),
            ('Move Piece', (-1, -2), (-2, -5)),
            ('Move Piece', (1, -3), (-2, 1)),
            ('Move Piece', (-2, -5), (1, -3)),
            ('Move Piece', (-2, 1), (0, -2)),
            ('Move Piece', (1, -3), (-2, -4)),
            ('Move Piece', (0, -2), (-2, -7)),
            ('Move Piece', (-4, 0), (-3, 1)),
            ('Move Piece', (-2, -7), (2, -1)),
            ('Move Piece', (-2, -4), (2, -2)),
            ('Move Piece', (-1, 1), (0, 1)),
            ('Move Piece', (2, -2), (3, 2)),
            ('Move Piece', (2, -1), (0, -1)),
            ('Move Piece', (3, 2), (1, -5)),
            ('Move Piece', (0, -1), (0, -7)),
            ('Move Piece', (1, -5), (0, 2)),
            ('Move Piece', (-1, -7), (0, -6)),
            ('Move Piece', (-1, -7), (1, -7)),
            ('Move Piece', (1, 0), (-4, 0)),
            ('Move Piece', (1, -7), (1, 2)),
            ('Move Piece', (0, -7), (3, 2)),
            ('Move Piece', (0, 2), (3, 1)),
            ('Move Piece', (3, 2), (-5, 0)),
            ('Move Piece', (1, 2), (-3, -4)),
            ('Move Piece', (-5, 0), (1, -6)),
            ('Move Piece', (-3, -4), (-2, -7)),
            ('Move Piece', (1, -6), (3, 0)),
            ('Move Piece', (-2, -7), (0, -2)),
            ('Move Piece', (3, 0), (4, 1)),
            ('Move Piece', (0, -2), (0, -7)),
            ('Move Piece', (4, 1), (0, -2)),
            ('Move Piece', (0, -7), (-4, -1)),
            ('Move Piece', (0, -2), (1, 0)),
            ('Move Piece', (3, 1), (1, -6)),
            ('Move Piece', (0, 1), (1, 2)),
            ('Move Piece', (1, -6), (2, -1)),
            ('Move Piece', (1, 0), (2, -2)),
            ('Move Piece', (-4, -1), (1, -4)),
            ('Move Piece', (0, -6), (-1, -6)),
            ('Move Piece', (1, -4), (-5, -1)),
            ('Move Piece', (2, -2), (-1, -7)),
            ('Move Piece', (-5, -1), (2, -2)),
            ('Move Piece', (-4, 0), (1, 0)),
            ('Move Piece', (2, -2), (2, 3)),
            ('Move Piece', (2, 1), (0, -1)),
            ('Move Piece', (2, -1), (2, 4)),
            ('Move Piece', (-1, -7), (-2, -5)),
            ('Move Piece', (2, 4), (-1, -7)),
            ('Move Piece', (-2, -5), (-2, -7)),
            ('Move Piece', (-1, -7), (3, 3)),
            ('Move Piece', (-2, -7), (-2, -5)),
            ('Move Piece', (3, 3), (0, -2)),
            ('Move Piece', (-2, -2), (1, -1)),
            ('Move Piece', (2, 3), (-2, -1)),
            ('Move Piece', (1, -1), (1, -2)),
            ('Move Piece', (-2, -1), (-3, -3)),
            ('Move Piece', (-2, -5), (2, 1)),
            ('Move Piece', (-3, -3), (-3, -4)),
            ('Move Piece', (1, -2), (-1, -7)),
            ('Move Piece', (-1, -1), (-1, 1)),
            ('Move Piece', (2, 0), (2, 1)),
            ('Move Piece', (-3, -4), (3, 1)),
            ('Move Piece', (2, 1), (1, 0)),
            ('Move Piece', (-1, 1), (-1, -1)),
            ('Move Piece', (-1, -7), (-1, 1)),
            ('Move Piece', (3, 1), (2, 2)),
            ('Move Piece', (-1, 1), (1, -5)),
            ('Move Piece', (2, 2), (0, -3)),
            ('Move Piece', (2, 1), (-4, 1)),
            ('Move Piece', (0, -3), (-2, 1)),
            ('Move Piece', (1, -5), (-2, -7)),
            ('Move Piece', (-2, 1), (-2, -5)),
            ('Move Piece', (-4, 1), (-3, -4)),
            ('Move Piece', (-2, -5), (2, 3)),
            ('Move Piece', (-2, -7), (-2, -6)),
            ('Move Piece', (2, 3), (-3, -6)),
            ('Move Piece', (-3, -4), (-4, -1)),
            ('Move Piece', (-3, -6), (-3, -7)),
            ('Move Piece', (-4, -1), (0, 1)),
            ('Move Piece', (-3, -7), (0, -6)),
            ('Move Piece', (0, 1), (1, -1)),
            ('Move Piece', (-3, 1), (-2, 1)),
            ('Move Piece', (1, -1), (-1, 2)),
            ('Move Piece', (0, -6), (1, -5)),
            ('Move Piece', (-1, 2), (-4, -1)),
            ('Move Piece', (1, -5), (-1, 2)),
            ('Move Piece', (-2, -6), (0, -6)),
            ('Move Piece', (-1, 2), (2, 3)),
            ('Move Piece', (0, -6), (-2, -4)),
            ('Move Piece', (2, 3), (1, -5)),
            ('Move Piece', (-4, -1), (-2, -5)),
            ('Move Piece', (1, -5), (-3, -1)),
            ('Move Piece', (-2, -5), (1, -2)),
            ('Move Piece', (-3, -1), (-1, 2)),
            ('Move Piece', (1, -2), (0, -6)),
            ('Move Piece', (-2, -3), (-2, -5)),
            ('Move Piece', (0, -6), (-4, -1)),
            ('Move Piece', (-1, 2), (2, 3)),
            ('Move Piece', (-2, -4), (-2, -2)),
            ('Move Piece', (2, 3), (-2, 2)),
            ('Move Piece', (-4, -1), (-3, -2)),
            ('Move Piece', (-2, 2), (2, 0)),
            ('Move Piece', (-1, -6), (-1, -5)),
            ('Move Piece', (2, 0), (0, 2)),
            ('Move Piece', (-3, -2), (1, -1)),
            ('Move Piece', (0, 2), (-4, 0)),
            ('Move Piece', (0, -5), (-1, 2)),
            ('Move Piece', (-4, 0), (0, -3)),
            ('Move Piece', (-1, 2), (1, 3)),
            ('Move Piece', (0, -3), (-3, -3)),
            ('Move Piece', (1, 3), (1, -4)),
            ('Move Piece', (-3, -3), (-3, -2)),
            ('Move Piece', (1, -4), (1, -2)),
            ('Move Piece', (-2, 1), (-2, 0)),
            ('Move Piece', (1, -1), (-3, -1)),
            ('Move Piece', (-3, -2), (1, 3)),
            ('Move Piece', (-3, -1), (-2, 1)),
            ('Move Piece', (1, 3), (2, 1)),
            ('Move Piece', (-2, 1), (-3, -2)),
            ('Move Piece', (2, 1), (2, 0)),
            ('Move Piece', (1, -2), (0, 2)),
            ('Move Piece', (2, 0), (1, -1)),
            ('Move Piece', (-3, -2), (2, 0)),
            ('Move Piece', (1, -1), (2, 3)),
            ('Move Piece', (2, 0), (-1, 1)),
            ('Move Piece', (-2, 0), (-2, -1)),
            ('Move Piece', (-2, -2), (-2, -3)),
            ('Move Piece', (2, 3), (-2, -4)),
            ('Move Piece', (-1, 1), (-2, -6)),
            ('Move Piece', (-1, 0), (-3, -4)),
            ('Move Piece', (0, 2), (-3, 1)),
            ('Move Piece', (-3, -4), (-4, -1)),
            ('Move Piece', (-3, 1), (2, 2)),
            ('Move Piece', (-4, -1), (-3, -2)),
            ('Move Piece', (-2, -3), (-4, -1)),
            ('Move Piece', (-2, -4), (2, 1)),
            ('Move Piece', (1, 0), (0, 0)),
            ('Move Piece', (-3, -2), (-4, 0)),
            ('Move Piece', (-1, -5), (-1, -6)),
            ('Move Piece', (-4, 0), (-4, -2)),
            ('Move Piece', (0, 0), (1, 0)),
            ('Move Piece', (2, 1), (-1, 0)),
            ('Move Piece', (2, 2), (-3, -5)),
            ('Move Piece', (-1, 0), (-3, -7)),
            ('Move Piece', (-3, -5), (-5, -2)),
            ('Move Piece', (-3, -7), (1, -4)),
            ('Move Piece', (1, 0), (2, 1)),
            ('Move Piece', (1, -4), (-3, 1)),
            ('Move Piece', (-5, -2), (0, 2)),
            ('Move Piece', (-3, 1), (0, -6)),
            ('Move Piece', (0, 2), (1, -5)),
            ('Move Piece', (-4, -2), (-2, -7)),
            ('Move Piece', (-4, -1), (1, 3)),
            ('Move Piece', (-3, 0), (-3, -1)),
        ]
        self._test_game_helper(actions)

    def test_game_two(self):
        actions = [
            ('Place Piece', (0, 0), 'Queen Bee'),
            ('Place Piece', (-1, 0), 'Ant'),
            ('Place Piece', (0, -1), 'Spider'),
            ('Place Piece', (-2, 0), 'Beetle'),
            ('Place Piece', (-1, -2), 'Ant'),
            ('Place Piece', (-1, 1), 'Ant'),
            ('Move Piece', (-1, -2), (-2, 1)),
            ('Place Piece', (0, 2), 'Queen Bee'),
            ('Move Piece', (-2, 1), (-2, -1)),
            ('Place Piece', (-1, 2), 'Beetle'),
            ('Move Piece', (-2, -1), (-1, -1)),
            ('Move Piece', (-2, 0), (-2, -1)),
            ('Place Piece', (0, -2), 'Spider'),
            ('Place Piece', (-1, 3), 'Spider'),
            ('Place Piece', (1, -1), 'Grasshopper'),
            ('Place Piece', (1, 3), 'Grasshopper'),
            ('Place Piece', (-1, -3), 'Ant'),
            ('Place Piece', (-2, 3), 'Grasshopper'),
            ('Move Piece', (-1, -1), (-2, 0)),
            ('Place Piece', (-2, 2), 'Spider'),
            ('Place Piece', (2, 0), 'Beetle'),
            ('Place Piece', (-1, 4), 'Grasshopper'),
            ('Place Piece', (2, 1), 'Grasshopper'),
            ('Move Piece', (-2, -1), (-3, -1)),
            ('Place Piece', (-2, -4), 'Beetle'),
            ('Move Piece', (-2, 2), (-4, -1)),
            ('Place Piece', (3, 1), 'Grasshopper'),
            ('Place Piece', (-4, -2), 'Ant'),
            ('Place Piece', (0, -3), 'Ant'),
            ('Move Piece', (-4, -1), (-2, 2)),
            ('Move Piece', (0, -3), (-2, -3)),
            ('Move Piece', (-4, -2), (2, 2)),
            ('Move Piece', (-2, -3), (-3, -5)),
            ('Move Piece', (2, 2), (-3, -2)),
            ('Move Piece', (-3, -5), (-3, 2)),
            ('Move Piece', (-3, -2), (1, 2)),
            ('Move Piece', (-3, 2), (-2, -5)),
            ('Move Piece', (1, 2), (-3, 2)),
            ('Move Piece', (3, 1), (-3, -5)),
            ('Move Piece', (-3, 2), (2, 4)),
            ('Move Piece', (-2, -5), (-3, -6)),
            ('Move Piece', (2, 4), (-3, 2)),
            ('Move Piece', (-3, -6), (0, 1)),
            ('Move Piece', (-1, 0), (0, 3)),
            ('Move Piece', (-3, -5), (3, 1)),
            ('Move Piece', (-3, 2), (4, 1)),
            ('Move Piece', (2, 1), (2, -1)),
            ('Move Piece', (4, 1), (3, -1)),
            ('Move Piece', (-2, -4), (-2, -3)),
            ('Move Piece', (3, -1), (-3, -4)),
            ('Move Piece', (3, 1), (-2, -4)),
            ('Move Piece', (0, 3), (-2, -5)),
            ('Move Piece', (-2, -3), (-3, -4)),
            ('Move Piece', (-2, -5), (1, 2)),
            ('Move Piece', (-3, -4), (-4, -4)),
            ('Move Piece', (1, 2), (2, 1)),
            ('Move Piece', (-4, -4), (-3, -3)),
            ('Move Piece', (2, 1), (-1, -4)),
            ('Move Piece', (2, -1), (-1, -1)),
            ('Move Piece', (-1, -4), (-3, 0)),
            ('Move Piece', (-1, -1), (2, -1)),
            ('Move Piece', (-3, 0), (1, 0)),
            ('Move Piece', (-3, -3), (-2, -3)),
            ('Move Piece', (-3, -4), (-3, 3)),
            ('Move Piece', (1, -1), (-1, -1)),
            ('Move Piece', (-3, 3), (3, -1)),
            ('Move Piece', (-2, -3), (-1, -2)),
            ('Move Piece', (-1, 4), (-1, 0)),
            ('Move Piece', (-1, -2), (-1, -3)),
            ('Move Piece', (-1, 0), (-3, 0)),
            ('Move Piece', (-1, -3), (-2, -4)),
            ('Move Piece', (3, -1), (2, 1)),
            ('Move Piece', (2, -1), (2, 2)),
            ('Move Piece', (-2, 3), (0, 3)),
            ('Move Piece', (-2, -4), (-3, -4)),
            ('Move Piece', (0, 3), (2, 3)),
            ('Move Piece', (2, 0), (3, 1)),
            ('Move Piece', (1, 0), (3, 0)),
            ('Move Piece', (-1, -1), (1, 1)),
            ('Move Piece', (3, 0), (-3, 1)),
            ('Move Piece', (-2, 0), (-1, 4)),
            ('Move Piece', (-1, 1), (1, -2)),
            ('Move Piece', (-1, 4), (-3, -5)),
            ('Move Piece', (-3, -1), (-2, 0)),
            ('Move Piece', (0, 1), (0, -3)),
            ('Move Piece', (1, -2), (-2, -1)),
            ('Move Piece', (0, -3), (-1, -4)),
            ('Move Piece', (-2, -1), (2, 0)),
            ('Move Piece', (-3, -5), (-4, -5)),
            ('Move Piece', (2, 0), (-4, -6)),
            ('Move Piece', (-1, -4), (-5, -7)),
            ('Move Piece', (-1, 3), (2, 4)),
            ('Move Piece', (-5, -7), (-3, 2)),
            ('Move Piece', (-4, -6), (-4, -4)),
            ('Move Piece', (-4, -5), (-2, -3)),
            ('Move Piece', (-4, -4), (3, 0)),
            ('Move Piece', (-3, 2), (-4, -1)),
            ('Move Piece', (3, 0), (-4, -2)),
            ('Move Piece', (-2, -3), (3, 2)),
            ('Move Piece', (2, 1), (-1, -4)),
            ('Move Piece', (-3, -4), (-2, -3)),
            ('Move Piece', (-1, -4), (-5, -2)),
            ('Move Piece', (-2, -3), (-1, -2)),
            ('Move Piece', (-5, -2), (-3, -1)),
            ('Move Piece', (-4, -1), (-2, -1)),
            ('Move Piece', (2, 4), (4, 3)),
            ('Move Piece', (-1, -2), (-2, -3)),
            ('Move Piece', (-4, -2), (-4, 0)),
            ('Move Piece', (-2, -1), (4, 2)),
            ('Move Piece', (-2, 0), (-2, 1)),
            ('Move Piece', (4, 2), (5, 3)),
            ('Move Piece', (-3, -1), (0, 3)),
            ('Move Piece', (5, 3), (4, 1)),
            ('Move Piece', (0, 3), (-4, -1)),
            ('Move Piece', (4, 1), (5, 4)),
            ('Move Piece', (-3, 1), (5, 5)),
            ('Move Piece', (3, 1), (3, 2)),
            ('Move Piece', (5, 5), (1, -1)),
            ('Move Piece', (3, 2), (4, 2)),
            ('Move Piece', (-4, -1), (-2, -2)),
            ('Move Piece', (4, 2), (4, 3)),
            ('Move Piece', (-4, 0), (-2, -5)),
            ('Move Piece', (5, 4), (0, -3)),
            ('Move Piece', (-2, -5), (-3, 2)),
            ('Move Piece', (4, 3), (5, 3)),
            ('Move Piece', (-2, -2), (-1, 3)),
            ('Move Piece', (0, -3), (3, 3)),
            ('Move Piece', (-1, 3), (-4, -1)),
            ('Move Piece', (3, 3), (-1, 3)),
            ('Move Piece', (-4, -1), (2, 0)),
            ('Move Piece', (-1, 3), (-1, -2)),
            ('Move Piece', (2, 0), (6, 4)),
            ('Move Piece', (-1, -2), (-1, 3)),
            ('Move Piece', (1, -1), (-3, -3)),
            ('Move Piece', (-1, 3), (0, 1)),
            ('Move Piece', (-3, -3), (4, 4)),
            ('Move Piece', (0, 1), (1, 0)),
            ('Move Piece', (-3, 2), (-4, -1)),
            ('Move Piece', (0, 0), (0, 1)),
            ('Move Piece', (-4, -1), (3, 4)),
            ('Move Piece', (3, 2), (0, 0)),
            ('Move Piece', (6, 4), (4, 5)),
            ('Move Piece', (1, 0), (-1, 1)),
            ('Move Piece', (4, 5), (-1, -2)),
            ('Move Piece', (-1, 1), (3, 5)),
            ('Move Piece', (-1, -2), (1, 4)),
            ('Move Piece', (5, 3), (4, 2)),
            ('Move Piece', (1, 4), (-4, 0)),
            ('Move Piece', (-2, -3), (-2, -4)),
            ('Move Piece', (-4, 0), (-3, -5)),
            ('Move Piece', (2, 2), (2, 4)),
            ('Move Piece', (-3, -5), (1, 4)),
            ('Move Piece', (-2, -4), (-1, -3)),
            ('Move Piece', (1, 4), (-1, -2)),
            ('Move Piece', (3, 5), (-1, -1)),
            ('Move Piece', (-1, -2), (-1, 3)),
            ('Move Piece', (-1, -1), (0, 3)),
            ('Move Piece', (-1, 3), (3, 3)),
            ('Move Piece', (1, 1), (-1, 1)),
            ('Move Piece', (3, 3), (-1, 0)),
            ('Move Piece', (-1, -3), (0, -3)),
            ('Move Piece', (-1, 0), (-1, -4)),
            ('Move Piece', (0, 3), (1, 1)),
            ('Move Piece', (-1, 2), (0, 3)),
            ('Move Piece', (-1, -3), (3, 3)),
            ('Move Piece', (3, 4), (2, 2)),
            ('Move Piece', (1, 1), (-4, -1)),
            ('Move Piece', (4, 4), (-4, -2)),
            ('Move Piece', (4, 2), (5, 3)),
            ('Move Piece', (2, 2), (5, 2)),
            ('Move Piece', (2, 4), (2, 2)),
            ('Move Piece', (-4, -2), (-1, -1)),
            ('Move Piece', (2, 2), (2, 4)),
            ('Move Piece', (-1, -1), (2, 2)),
            ('Move Piece', (-4, -1), (6, 2)),
            ('Move Piece', (2, 2), (-2, 0)),
            ('Move Piece', (6, 2), (-2, 3)),
            ('Move Piece', (-2, 0), (1, -2)),
            ('Move Piece', (-2, 3), (3, 5)),
            ('Move Piece', (5, 2), (4, 5)),
            ('Move Piece', (5, 3), (4, 2)),
            ('Move Piece', (1, -2), (4, 1)),
            ('Move Piece', (-2, -4), (0, -4)),
            ('Move Piece', (-1, -4), (1, 0)),
            ('Move Piece', (0, -4), (0, 4)),
            ('Move Piece', (-2, 2), (-4, -1)),
            ('Move Piece', (0, 4), (0, -4)),
            ('Move Piece', (4, 5), (1, -1)),
            ('Move Piece', (3, 5), (1, 2)),
            ('Move Piece', (1, 0), (3, 4)),
            ('Move Piece', (1, 2), (4, 5)),
            ('Move Piece', (-4, -1), (-1, 0)),
            ('Move Piece', (4, 5), (-1, 3)),
            ('Move Piece', (1, -1), (2, 5)),
            ('Move Piece', (-1, 3), (-1, -2)),
            ('Move Piece', (3, 4), (5, 2)),
            ('Move Piece', (-1, -2), (3, 1)),
            ('Move Piece', (0, 3), (-1, 2)),
            ('Move Piece', (3, 1), (-1, 3)),
            ('Move Piece', (2, 5), (5, 3)),
            ('Move Piece', (-1, 3), (-4, 0)),
            ('Move Piece', (4, 1), (1, 0)),
            ('Move Piece', (-4, 0), (3, 4)),
            ('Move Piece', (5, 3), (1, -2)),
            ('Move Piece', (2, 4), (-2, 0)),
            ('Move Piece', (1, -2), (-1, -4)),
            ('Move Piece', (0, -4), (-2, -4)),
            ('Move Piece', (5, 2), (-2, 2)),
            ('Move Piece', (4, 2), (5, 3)),
            ('Move Piece', (1, 0), (3, 5)),
            ('Move Piece', (5, 3), (4, 2)),
            ('Move Piece', (-2, 2), (0, 3)),
            ('Move Piece', (4, 2), (5, 3)),
            ('Move Piece', (3, 5), (1, -2)),
            ('Move Piece', (3, 4), (-2, 2)),
            ('Move Piece', (0, 3), (4, 2)),
            ('Move Piece', (-2, 2), (0, 3)),
            ('Move Piece', (1, -2), (-1, 3)),
            ('Move Piece', (-2, 0), (2, 4)),
            ('Move Piece', (4, 2), (5, 2)),
            ('Move Piece', (0, 3), (-3, -5)),
            ('Move Piece', (-1, 3), (-2, -3)),
            ('Move Piece', (-3, -5), (-4, 0)),
            ('Move Piece', (5, 2), (1, 1)),
            ('Move Piece', (5, 3), (5, 4)),
            ('Move Piece', (-2, -3), (-3, -4)),
            ('Move Piece', (-4, 0), (-1, -1)),
            ('Move Piece', (1, 1), (5, 3)),
            ('Move Piece', (-1, -1), (6, 5)),
            ('Move Piece', (5, 3), (3, 5)),
            ('Move Piece', (6, 5), (1, 0)),
            ('Move Piece', (-3, -4), (1, 1)),
            ('Move Piece', (1, 0), (1, 4)),
            ('Move Piece', (1, 1), (3, 2)),
            ('Move Piece', (1, 4), (6, 4)),
            ('Move Piece', (3, 2), (6, 3)),
            ('Move Piece', (0, 1), (1, 2)),
            ('Move Piece', (3, 5), (-2, 0)),
            ('Move Piece', (-1, 1), (-3, 1)),
            ('Move Piece', (1, 3), (5, 3)),
            ('Move Piece', (-3, 1), (-3, -1)),
            ('Move Piece', (6, 3), (1, -2)),
            ('Move Piece', (6, 4), (0, 3)),
            ('Move Piece', (1, -2), (5, 2)),
            ('Move Piece', (0, 3), (2, 5)),
            ('Move Piece', (5, 2), (4, 2)),
            ('Move Piece', (2, 5), (6, 5)),
            ('Move Piece', (5, 3), (5, 5)),
            ('Move Piece', (6, 5), (-2, -1)),
            ('Move Piece', (4, 2), (5, 3)),
            ('Move Piece', (-2, -1), (-1, -3)),
            ('Move Piece', (-1, -4), (-4, -1)),
            ('Move Piece', (2, 4), (2, 2)),
            ('Move Piece', (-4, -1), (-2, -1)),
            ('Move Piece', (2, 2), (2, 4)),
            ('Move Piece', (5, 3), (0, 3)),
            ('Move Piece', (-3, -1), (-3, 1)),
            ('Move Piece', (-2, -1), (-4, -1)),
            ('Move Piece', (0, -3), (0, -2)),
            ('Move Piece', (-4, -1), (-3, -1)),
            ('Move Piece', (0, -2), (0, -3)),
            ('Move Piece', (-3, -1), (-1, 3)),
            ('Move Piece', (0, -3), (-1, -4)),
            ('Move Piece', (-1, 3), (-2, -5)),
            ('Move Piece', (-3, 1), (-1, 1)),
            ('Move Piece', (0, 3), (4, 4)),
            ('Move Piece', (5, 4), (5, 3)),
            ('Move Piece', (-2, 0), (-2, -6)),
            ('Move Piece', (-2, -4), (-2, -7)),
            ('Move Piece', (-1, 2), (0, 3)),
            ('Move Piece', (-2, -7), (-2, -4)),
            ('Move Piece', (-2, -6), (-3, -1)),
            ('Move Piece', (-1, -4), (-1, -3)),
            ('Move Piece', (-2, -5), (-4, -2)),
            ('Move Piece', (5, 3), (4, 2)),
            ('Move Piece', (-4, -2), (-1, 2)),
            ('Move Piece', (4, 2), (4, 3)),
            ('Move Piece', (-1, 2), (5, 4)),
            ('Move Piece', (4, 3), (3, 2)),
            ('Move Piece', (-3, -1), (-2, -5)),
            ('Move Piece', (3, 2), (3, 3)),
            ('Move Piece', (5, 4), (5, 6)),
            ('Move Piece', (-1, -3), (0, -2)),
            ('Move Piece', (-2, -5), (0, -3)),
            ('Move Piece', (0, -2), (0, -1)),
            ('Move Piece', (0, -3), (-2, -5)),
            ('Move Piece', (0, -1), (1, 0)),
            ('Move Piece', (5, 6), (0, -3)),
            ('Move Piece', (2, 4), (2, 2)),
            ('Move Piece', (0, -3), (-3, -5)),
            ('Move Piece', (2, 2), (2, 4)),
            ('Move Piece', (-3, -5), (1, -1)),
            ('Move Piece', (3, 3), (2, 3)),
            ('Move Piece', (1, -1), (6, 5)),
            ('Move Piece', (2, 3), (3, 4)),
            ('Move Piece', (6, 5), (3, 2)),
            ('Move Piece', (1, 0), (1, 1)),
            ('Move Piece', (3, 2), (-2, -6)),
            ('Move Piece', (1, 1), (1, 0)),
            ('Move Piece', (0, 3), (1, 3)),
            ('Move Piece', (3, 3), (-1, -4)),
            ('Move Piece', (-2, -6), (5, 4)),
            ('Move Piece', (1, 2), (0, 1)),
            ('Move Piece', (5, 5), (3, 3)),
            ('Move Piece', (-2, -4), (1, -1)),
            ('Move Piece', (-2, -5), (4, 2)),
            ('Move Piece', (0, -1), (-2, 0)),
            ('Move Piece', (4, 2), (-1, -5)),
            ('Move Piece', (3, 4), (2, 4)),
            ('Move Piece', (-1, -5), (1, 1)),
            ('Move Piece', (0, 0), (2, 1)),
            ('Move Piece', (4, 4), (0, 0)),
            ('Move Piece', (-1, -4), (2, -1)),
            ('Move Piece', (5, 4), (-1, -2)),
            ('Move Piece', (2, 4), (1, 3)),
            ('Move Piece', (-1, -2), (-2, -3)),
            ('Move Piece', (2, 1), (3, 0)),
            ('Move Piece', (0, 0), (0, 3)),
            ('Move Piece', (3, 0), (5, 4)),
            ('Move Piece', (-2, 1), (-3, 0)),
            ('Move Piece', (2, -1), (-1, 3)),
            ('Move Piece', (-2, -3), (5, 3)),
            ('Move Piece', (-1, 3), (-2, -4)),
            ('Move Piece', (-3, 0), (-4, 0)),
            ('Move Piece', (5, 4), (-3, -1)),
            ('Move Piece', (0, 3), (-4, -1)),
            ('Move Piece', (-3, -1), (-3, -5)),
            ('Move Piece', (-4, -1), (5, 2)),
            ('Move Piece', (-3, -5), (1, 4)),
            ('Move Piece', (5, 2), (2, -1)),
            ('Move Piece', (-2, -4), (2, 5)),
            ('Move Piece', (5, 3), (2, 0)),
            ('Move Piece', (-1, 1), (-1, -1)),
            ('Move Piece', (-4, 0), (-4, -1)),
            ('Move Piece', (2, 5), (2, 2)),
            ('Move Piece', (2, 0), (2, 5)),
            ('Move Piece', (2, 2), (4, 4)),
            ('Move Piece', (2, -1), (-5, -2)),
            ('Move Piece', (4, 4), (2, -1)),
            ('Move Piece', (2, 5), (2, 2)),
            ('Move Piece', (2, -1), (0, 4)),
            ('Move Piece', (-5, -2), (-2, -2)),
            ('Move Piece', (-1, -3), (-1, 3)),
            ('Move Piece', (-2, -2), (-3, 1)),
            ('Move Piece', (-1, 3), (-4, 1)),
            ('Move Piece', (2, 2), (-1, -3)),
            ('Move Piece', (-4, 1), (1, 5)),
            ('Move Piece', (-3, 1), (1, -2)),
            ('Move Piece', (0, 4), (-5, -1)),
            ('Move Piece', (-1, -3), (2, 6)),
            ('Move Piece', (1, 3), (0, 3)),
            ('Move Piece', (1, 3), (2, 3)),
            ('Move Piece', (-5, -1), (-4, 0)),
            ('Move Piece', (2, 3), (2, 4)),
            ('Move Piece', (-4, 0), (2, -1)),
            ('Move Piece', (-4, -1), (-4, 0)),
            ('Move Piece', (2, -1), (-4, 1)),
            ('Move Piece', (2, 6), (0, 4)),
            ('Move Piece', (1, 5), (-1, -2)),
            ('Move Piece', (0, 4), (4, 2)),
            ('Move Piece', (-4, 1), (2, 5)),
            ('Move Piece', (4, 2), (-1, 1)),
            ('Move Piece', (2, 5), (-4, 1)),
            ('Move Piece', (1, -2), (-3, -1)),
            ('Move Piece', (-1, -2), (-2, 1)),
            ('Move Piece', (4, 3), (3, 5)),
            ('Move Piece', (-4, 1), (-1, 3)),
            ('Move Piece', (3, 5), (0, 4)),
            ('Move Piece', (-2, 1), (1, -2)),
            ('Move Piece', (-3, -1), (-1, -3)),
            ('Move Piece', (-1, 3), (4, 4)),
            ('Move Piece', (-1, -3), (-1, -2)),
            ('Move Piece', (1, 0), (0, -1)),
            ('Move Piece', (1, 1), (0, -3)),
            ('Move Piece', (1, -2), (-1, 3)),
            ('Move Piece', (-1, 1), (-4, 1)),
            ('Move Piece', (-1, 3), (-3, 2)),
            ('Move Piece', (-1, -2), (-1, 4)),
            ('Move Piece', (4, 4), (-4, -1)),
            ('Move Piece', (-1, 4), (-2, -2)),
            ('Move Piece', (1, -1), (-1, -3)),
            ('Move Piece', (-2, -2), (1, 1)),
            ('Move Piece', (-3, 2), (-3, 1)),
            ('Move Piece', (0, -3), (-2, -2)),
            ('Move Piece', (-3, 1), (0, -3)),
            ('Move Piece', (1, 1), (-1, 3)),
            ('Move Piece', (0, -3), (4, 3)),
            ('Move Piece', (-1, 3), (-2, -1)),
            ('Move Piece', (-4, -1), (-1, 3)),
            ('Move Piece', (-2, -1), (-3, -2)),
            ('Move Piece', (-1, 3), (1, -1)),
            ('Move Piece', (-4, 1), (5, 3)),
            ('Move Piece', (1, -1), (-4, -3)),
            ('Move Piece', (5, 3), (3, 5)),
            ('Move Piece', (-4, -3), (5, 4)),
            ('Move Piece', (2, 4), (3, 4)),
            ('Move Piece', (5, 4), (1, -2)),
            ('Move Piece', (2, 3), (4, 5)),
            ('Move Piece', (4, 3), (1, 3)),
            ('Move Piece', (3, 5), (2, 3)),
            ('Move Piece', (1, 4), (2, 2)),
            ('Move Piece', (-3, -2), (2, -2)),
            ('Move Piece', (2, 4), (4, 4)),
            ('Move Piece', (2, -2), (-4, 1)),
            ('Move Piece', (-1, -3), (1, -1)),
            ('Move Piece', (-2, -2), (2, 1)),
            ('Move Piece', (4, 4), (2, 4)),
            ('Move Piece', (-4, 1), (5, 5)),
            ('Move Piece', (1, -2), (2, 5)),
            ('Move Piece', (5, 5), (-1, 2)),
            ('Move Piece', (2, 5), (1, 5)),
            ('Move Piece', (3, 3), (-1, 3)),
            ('Move Piece', (2, 4), (4, 4)),
            ('Move Piece', (2, 1), (5, 5)),
            ('Move Piece', (2, 2), (1, -2)),
            ('Move Piece', (-1, 2), (0, -3)),
            ('Move Piece', (1, 5), (1, -3)),
            ('Move Piece', (0, -3), (1, 2)),
            ('Move Piece', (1, -3), (-4, -1)),
            ('Move Piece', (-1, 3), (3, 3)),
            ('Move Piece', (1, -2), (3, 5)),
            ('Move Piece', (1, 2), (5, 6)),
            ('Move Piece', (4, 4), (4, 6)),
            ('Move Piece', (5, 5), (4, 4)),
            ('Move Piece', (3, 5), (-1, 3)),
            ('Move Piece', (3, 3), (5, 5)),
            ('Move Piece', (-1, 3), (6, 5)),
            ('Move Piece', (4, 4), (5, 4)),
            ('Move Piece', (-4, -1), (1, 4)),
            ('Move Piece', (-4, 0), (-4, -1)),
            ('Move Piece', (6, 5), (2, 2)),
            ('Move Piece', (-4, -1), (-3, 0)),
            ('Move Piece', (1, 4), (-2, 1)),
            ('Move Piece', (5, 6), (-2, 2)),
            ('Move Piece', (2, 2), (1, 5)),
            ('Move Piece', (5, 4), (1, 6)),
            ('Move Piece', (0, -2), (-2, -1)),
            ('Move Piece', (1, 6), (4, 7)),
            ('Move Piece', (1, 5), (5, 8)),
            ('Move Piece', (-2, 2), (4, 8)),
            ('Move Piece', (-2, 1), (4, 9)),
            ('Move Piece', (-3, 0), (-3, -1)),
            ('Move Piece', (5, 8), (-4, 0)),
            ('Move Piece', (-3, -1), (-2, -1)),
            ('Move Piece', (-4, 0), (1, 2)),
            ('Move Piece', (-2, -1), (-3, -1)),
            ('Move Piece', (1, 2), (-4, -2)),
            ('Move Piece', (0, 4), (3, 5)),
            ('Move Piece', (-4, -2), (3, 7)),
            ('Move Piece', (-3, 0), (0, 0)),
            ('Move Piece', (3, 7), (2, 5)),
            ('Move Piece', (0, 0), (0, -2)),
            ('Move Piece', (2, 5), (1, 0)),
            ('Move Piece', (0, -2), (2, 0)),
            ('Move Piece', (1, 0), (5, 4)),
            ('Move Piece', (-3, -1), (-2, -1)),
            ('Move Piece', (5, 4), (-2, 1)),
            ('Move Piece', (2, 0), (0, -2)),
            ('Move Piece', (4, 9), (5, 8)),
            ('Move Piece', (4, 8), (-1, -3)),
            ('Move Piece', (-2, 1), (0, 4)),
            ('Move Piece', (-1, -3), (0, -3)),
            ('Move Piece', (5, 8), (-1, -4)),
            ('Move Piece', (-2, -1), (-3, -1)),
            ('Move Piece', (-1, -4), (2, -1)),
            ('Move Piece', (0, -3), (4, 4)),
            ('Move Piece', (0, 4), (-3, 0)),
            ('Move Piece', (4, 4), (1, 4)),
            ('Move Piece', (-3, 0), (0, 4)),
            ('Move Piece', (4, 7), (0, 0)),
            ('Move Piece', (2, -1), (5, 6)),
            ('Move Piece', (0, 0), (2, 0)),
            ('Move Piece', (0, 4), (-1, -2)),
            ('Move Piece', (1, 4), (1, 1)),
            ('Move Piece', (-1, -2), (3, 6)),
            ('Move Piece', (1, 1), (3, 3)),
            ('Move Piece', (3, 6), (6, 5)),
            ('Move Piece', (2, 0), (1, -2)),
            ('Move Piece', (5, 6), (2, 5)),
            ('Move Piece', (3, 3), (5, 6)),
            ('Move Piece', (2, 5), (5, 4)),
            ('Move Piece', (1, -2), (6, 6)),
            ('Move Piece', (5, 4), (3, 3)),
            ('Move Piece', (6, 6), (2, -1)),
            ('Move Piece', (3, 3), (1, 1)),
            ('Move Piece', (5, 6), (0, 4)),
            ('Move Piece', (1, 1), (0, 0)),
            ('Move Piece', (0, 4), (7, 5)),
            ('Move Piece', (0, 0), (-1, 2)),
            ('Move Piece', (2, -1), (3, 6)),
            ('Move Piece', (0, 3), (-1, 2)),
            ('Move Piece', (7, 5), (5, 7)),
            ('Move Piece', (6, 5), (-3, 0)),
            ('Move Piece', (3, 6), (2, 4)),
            ('Move Piece', (-3, 0), (3, 6)),
            ('Move Piece', (2, 3), (-1, -2)),
            ('Move Piece', (-1, 2), (0, 3)),
            ('Move Piece', (-3, -1), (-2, -1)),
            ('Move Piece', (0, 3), (0, 2)),
            ('Move Piece', (-1, -2), (0, -3)),
            ('Move Piece', (-2, 0), (-2, -2)),
            ('Move Piece', (5, 7), (1, -3)),
            ('Move Piece', (-1, 2), (-1, -4)),
            ('Move Piece', (1, -3), (0, 3)),
            ('Move Piece', (-1, -4), (-2, 0)),
            ('Move Piece', (0, 3), (-3, -1)),
            ('Move Piece', (3, 6), (-1, 1)),
            ('Move Piece', (-3, -1), (3, 6)),
            ('Move Piece', (-2, 0), (2, 6)),
            ('Move Piece', (-2, -1), (-2, -2)),
            ('Move Piece', (-1, 1), (-3, -3)),
            ('Move Piece', (3, 4), (4, 5)),
            ('Move Piece', (2, 6), (4, 7)),
            ('Move Piece', (0, -3), (-1, -2)),
            ('Move Piece', (4, 7), (4, 4)),
            ('Move Piece', (-1, -2), (-1, -3)),
            ('Move Piece', (4, 4), (6, 5)),
            ('Move Piece', (-1, -3), (-3, -4)),
            ('Move Piece', (6, 5), (2, 0)),
            ('Move Piece', (3, 6), (-4, -3)),
            ('Move Piece', (2, 0), (6, 5)),
            ('Move Piece', (-4, -3), (5, 6)),
            ('Move Piece', (6, 5), (-1, 1)),
            ('Move Piece', (-3, -4), (-2, 0)),
            ('Move Piece', (-1, 1), (1, 0)),
            ('Move Piece', (-2, 0), (-4, -3)),
            ('Move Piece', (1, 0), (4, 4)),
            ('Move Piece', (-4, -3), (2, -1)),
            ('Move Piece', (4, 4), (4, 7)),
            ('Move Piece', (4, 5), (3, 5)),
            ('Move Piece', (4, 7), (-4, -3)),
            ('Move Piece', (5, 6), (-1, -2)),
            ('Move Piece', (-4, -3), (0, 0)),
            ('Move Piece', (-2, -2), (-1, -1)),
            ('Move Piece', (0, 0), (3, -1)),
            ('Move Piece', (-1, -1), (0, 0)),
            ('Move Piece', (3, -1), (4, 7)),
            ('Move Piece', (-1, -2), (-4, -4)),
            ('Move Piece', (4, 7), (-1, -2)),
            ('Move Piece', (-4, -4), (1, 1)),
            ('Move Piece', (-3, -3), (-1, 1)),
            ('Move Piece', (0, 0), (0, 1)),
            ('Move Piece', (-1, 1), (6, 5)),
            ('Move Piece', (2, -1), (2, 0)),
            ('Move Piece', (6, 5), (-2, -3)),
            ('Move Piece', (1, 1), (5, 7)),
            ('Move Piece', (0, -1), (-1, -1)),
            ('Move Piece', (2, 0), (5, 6)),
            ('Move Piece', (-2, -3), (0, -1)),
            ('Move Piece', (5, 6), (3, 4)),
            ('Move Piece', (-1, -2), (-2, 0)),
            ('Move Piece', (3, 5), (3, 6)),
            ('Move Piece', (-2, 0), (0, 0)),
            ('Move Piece', (0, 1), (-1, 0)),
            ('Move Piece', (0, 0), (0, 3)),
            ('Move Piece', (3, 4), (-1, 2)),
            ('Move Piece', (0, 3), (-2, 1)),
            ('Move Piece', (-1, 0), (-1, -1)),
            ('Move Piece', (-2, 1), (-3, -1)),
            ('Move Piece', (-1, 2), (3, 7)),
            ('Move Piece', (-3, -1), (1, 2)),
            ('Move Piece', (5, 7), (0, 3)),
            ('Move Piece', (1, -1), (-3, -1)),
            ('Move Piece', (3, 7), (-4, -2)),
            ('Move Piece', (1, 2), (2, 6)),
            ('Move Piece', (-4, -2), (0, 4)),
            ('Move Piece', (2, 6), (0, 5)),
            ('Move Piece', (3, 6), (2, 5)),
            ('Move Piece', (0, 2), (0, 1)),
            ('Move Piece', (2, 5), (3, 5)),
            ('Move Piece', (0, 5), (5, 7)),
            ('Move Piece', (0, 4), (1, 1)),
            ('Move Piece', (0, 1), (-1, 1)),
            ('Move Piece', (1, 1), (3, 4)),
            ('Move Piece', (5, 7), (6, 6)),
            ('Move Piece', (0, 3), (5, 7)),
            ('Move Piece', (6, 6), (1, -2)),
            ('Move Piece', (3, 4), (-4, -1)),
            ('Move Piece', (-1, 1), (0, 1)),
            ('Move Piece', (-1, -1), (-1, -2)),
            ('Move Piece', (0, -1), (-4, 0)),
            ('Move Piece', (3, 5), (4, 5)),
            ('Move Piece', (-4, 0), (6, 6)),
            ('Move Piece', (-4, -1), (4, 4)),
            ('Move Piece', (6, 6), (-1, 2)),
            ('Move Piece', (4, 4), (0, -1)),
            ('Move Piece', (-1, -1), (-1, 0)),
            ('Move Piece', (5, 7), (4, 4)),
            ('Move Piece', (-1, 2), (5, 6)),
            ('Move Piece', (-1, -2), (0, -2)),
            ('Move Piece', (-1, 0), (-2, -1)),
            ('Move Piece', (4, 4), (1, 2)),
            ('Move Piece', (5, 6), (6, 6)),
            ('Move Piece', (0, -2), (1, -1)),
            ('Move Piece', (6, 6), (-1, 2)),
            ('Move Piece', (4, 5), (5, 6)),
            ('Move Piece', (1, -2), (6, 7)),
            ('Move Piece', (1, 2), (1, 0)),
            ('Move Piece', (-1, 2), (-3, -2)),
            ('Move Piece', (1, 0), (0, 3)),
            ('Move Piece', (4, 6), (6, 6)),
            ('Move Piece', (0, -2), (0, 0)),
            ('Move Piece', (-3, -2), (1, 1)),
            ('Move Piece', (0, 0), (-2, 0)),
            ('Move Piece', (6, 7), (4, 6)),
            ('Move Piece', (5, 5), (2, 5)),
            ('Move Piece', (4, 6), (1, 5)),
            ('Move Piece', (0, 3), (1, 2)),
            ('Move Piece', (1, 1), (-3, -3)),
            ('Move Piece', (1, 2), (0, 3)),
            ('Move Piece', (1, 5), (4, 6)),
            ('Move Piece', (0, 3), (-3, -2)),
            ('Move Piece', (-3, -3), (2, -1)),
            ('Move Piece', (-3, -2), (3, 4)),
            ('Move Piece', (-2, -1), (-3, -1)),
            ('Move Piece', (3, 4), (2, 3)),
            ('Move Piece', (4, 6), (-4, -1)),
            ('Move Piece', (-2, 0), (-2, -3)),
            ('Move Piece', (2, -1), (5, 7)),
            ('Move Piece', (2, 3), (1, 5)),
            ('Move Piece', (5, 7), (-3, 0)),
            ('Move Piece', (1, 5), (1, 1)),
            ('Move Piece', (-3, 0), (2, 1)),
            ('Move Piece', (1, -1), (0, -1)),
            ('Move Piece', (-4, -1), (-2, -4)),
            ('Move Piece', (0, -1), (-1, -2)),
            ('Move Piece', (2, 1), (1, 2)),
            ('Move Piece', (0, -1), (5, 7)),
            ('Move Piece', (1, 2), (1, 4)),
            ('Move Piece', (5, 7), (3, 4)),
            ('Move Piece', (1, 4), (0, 0)),
            ('Move Piece', (1, 1), (-3, 0)),
            ('Move Piece', (-2, -4), (3, 3)),
            ('Move Piece', (-3, 0), (0, -2)),
            ('Move Piece', (-1, -1), (-3, -3)),
            ('Move Piece', (0, -2), (1, 2)),
            ('Move Piece', (0, 0), (1, 1)),
            ('Move Piece', (1, 2), (1, 4)),
            ('Move Piece', (3, 3), (6, 7)),
            ('Move Piece', (3, 5), (1, 5)),
            ('Move Piece', (6, 7), (2, 6)),
            ('Move Piece', (1, 4), (-2, -4)),
            ('Move Piece', (2, 6), (1, 6)),
            ('Move Piece', (-2, -4), (4, 6)),
            ('Move Piece', (1, 6), (7, 6)),
            ('Move Piece', (4, 6), (2, 3)),
            ('Move Piece', (7, 6), (0, -1)),
            ('Move Piece', (2, 3), (0, 5)),
            ('Move Piece', (1, 1), (1, 2)),
            ('Move Piece', (0, 5), (-4, -3)),
            ('Move Piece', (0, -1), (-2, -4)),
            ('Move Piece', (-4, -3), (3, 5)),
            ('Move Piece', (-2, -4), (1, 4)),
            ('Move Piece', (2, 5), (0, 5)),
            ('Move Piece', (1, 2), (7, 6)),
            ('Move Piece', (3, 4), (-4, -2)),
            ('Move Piece', (7, 6), (1, 1)),
            ('Move Piece', (-1, -2), (-2, -2)),
            ('Move Piece', (-3, -1), (-4, -2)),
            ('Move Piece', (-2, -3), (-2, 0)),
            ('Move Piece', (0, 1), (1, 1)),
            ('Move Piece', (-2, -2), (-1, -1)),
            ('Move Piece', (-4, -2), (-3, -1)),
            ('Move Piece', (-4, -2), (0, -1)),
            ('Move Piece', (-3, -1), (-3, -2)),
            ('Move Piece', (0, -1), (-2, 1)),
            ('Move Piece', (6, 6), (4, 6)),
            ('Move Piece', (-2, 1), (0, -1)),
            ('Move Piece', (-3, -1), (2, -1)),
        ]
        self.assertRaisesRegex(
            RuntimeError,
            "Illegal action. This piece cannot move to the specified location.",
            self._test_game_helper,
            actions
        )

    def test_game_three(self):
        actions = [
            ('Place Piece', (0, 0), 'Ant'),
            ('Place Piece', (1, 1), 'Grasshopper'),
            ('Place Piece', (0, -1), 'Ant'),
            ('Place Piece', (1, 2), 'Ant'),
            ('Place Piece', (-1, -2), 'Queen Bee'),
            ('Place Piece', (2, 3), 'Grasshopper'),
            ('Place Piece', (0, -2), 'Beetle'),
            ('Place Piece', (0, 2), 'Queen Bee'),
            ('Place Piece', (1, -1), 'Spider'),
            ('Place Piece', (2, 1), 'Spider'),
            ('Place Piece', (-1, -1), 'Beetle'),
            ('Move Piece', (0, 2), (0, 1)),
            ('Place Piece', (-2, -1), 'Grasshopper'),
            ('Place Piece', (3, 1), 'Beetle'),
            ('Place Piece', (-2, 0), 'Spider'),
            ('Place Piece', (1, 3), 'Ant'),
            ('Move Piece', (-2, 0), (0, 2)),
            ('Move Piece', (1, 3), (-3, -2)),
            ('Place Piece', (0, -3), 'Grasshopper'),
            ('Move Piece', (3, 1), (2, 1)),
            ('Place Piece', (2, -1), 'Grasshopper'),
            ('Move Piece', (-3, -2), (2, 4)),
            ('Place Piece', (-2, -3), 'Ant'),
            ('Place Piece', (1, 4), 'Grasshopper'),
            ('Move Piece', (-2, -3), (-1, -3)),
            ('Place Piece', (2, 2), 'Spider'),
            ('Move Piece', (-1, -3), (0, 4)),
            ('Place Piece', (3, 1), 'Ant'),
            ('Move Piece', (0, 4), (0, -4)),
            ('Move Piece', (3, 1), (-2, -3)),
            ('Move Piece', (0, -4), (1, -2)),
            ('Move Piece', (-2, -3), (2, -2)),
            ('Move Piece', (0, 2), (-2, 0)),
            ('Place Piece', (1, 3), 'Beetle'),
            ('Move Piece', (-2, 0), (0, 2)),
            ('Move Piece', (2, -2), (2, 5)),
            ('Move Piece', (1, -2), (-1, -3)),
            ('Move Piece', (2, 4), (3, 5)),
            ('Move Piece', (-1, -3), (3, 4)),
            ('Move Piece', (2, 5), (-2, -3)),
            ('Move Piece', (0, 2), (1, 5)),
            ('Move Piece', (0, 1), (0, 2)),
            ('Move Piece', (1, 5), (-1, 2)),
            ('Move Piece', (2, 2), (2, 0)),
            ('Move Piece', (0, 0), (0, 4)),
            ('Move Piece', (3, 5), (3, 3)),
            ('Move Piece', (0, -1), (2, 4)),
            ('Move Piece', (3, 3), (-3, -2)),
            ('Move Piece', (0, 4), (1, -3)),
            ('Move Piece', (-3, -2), (2, 5)),
            ('Move Piece', (3, 4), (-3, -2)),
            ('Move Piece', (-2, -3), (3, 1)),
            ('Move Piece', (2, 4), (0, 4)),
            ('Move Piece', (3, 1), (3, 5)),
            ('Move Piece', (1, -3), (-4, -2)),
            ('Move Piece', (3, 5), (0, 5)),
            ('Move Piece', (-4, -2), (3, 4)),
            ('Move Piece', (0, 5), (0, -1)),
            ('Move Piece', (0, 4), (4, 5)),
            ('Move Piece', (0, -1), (0, 4)),
            ('Move Piece', (-3, -2), (3, 6)),
            ('Move Piece', (0, 4), (1, 0)),
            ('Move Piece', (3, 6), (3, 1)),
            ('Move Piece', (2, 5), (-2, 1)),
            ('Move Piece', (3, 1), (-3, -2)),
            ('Move Piece', (1, 0), (1, -2)),
            ('Move Piece', (4, 5), (0, -4)),
            ('Move Piece', (-2, 1), (-1, -5)),
            ('Move Piece', (-3, -2), (-3, -1)),
            ('Move Piece', (-1, -5), (-2, -2)),
            ('Move Piece', (3, 4), (1, 0)),
            ('Move Piece', (-2, -2), (3, 3)),
            ('Move Piece', (1, 0), (2, 5)),
            ('Move Piece', (3, 3), (-2, -2)),
            ('Move Piece', (0, -4), (-4, -2)),
            ('Move Piece', (1, -2), (-3, 0)),
            ('Move Piece', (2, 5), (1, 5)),
            ('Move Piece', (-2, -2), (-2, 2)),
            ('Move Piece', (-4, -2), (-3, 2)),
            ('Move Piece', (-3, 0), (1, 0)),
            ('Move Piece', (1, 5), (-2, 0)),
            ('Move Piece', (1, 0), (-1, 0)),
            ('Move Piece', (-2, 0), (-4, 2)),
            ('Move Piece', (1, 4), (1, 0)),
            ('Move Piece', (-4, 2), (1, -3)),
            ('Move Piece', (-1, 0), (-2, -3)),
            ('Move Piece', (1, -3), (3, 4)),
            ('Move Piece', (-2, -3), (1, -2)),
            ('Move Piece', (-3, 2), (-3, -2)),
            ('Move Piece', (1, -2), (1, 4)),
            ('Move Piece', (-3, -2), (1, 5)),
            ('Move Piece', (-2, 2), (-2, 0)),
            ('Move Piece', (3, 4), (-2, 1)),
            ('Move Piece', (2, 3), (0, 3)),
            ('Move Piece', (1, 5), (3, 0)),
            ('Move Piece', (0, 2), (0, 1)),
            ('Move Piece', (-3, -1), (1, 5)),
            ('Move Piece', (2, 1), (1, 1)),
            ('Move Piece', (3, 0), (-1, -4)),
            ('Move Piece', (-2, 0), (-3, 0)),
            ('Move Piece', (1, 5), (-1, -5)),
            ('Move Piece', (1, 4), (-2, -6)),
            ('Move Piece', (2, -1), (2, 2)),
            ('Move Piece', (-2, -6), (-1, 3)),
            ('Move Piece', (-1, -5), (-1, -3)),
            ('Move Piece', (1, 0), (3, 2)),
            ('Move Piece', (-1, -4), (3, 1)),
            ('Move Piece', (-3, 0), (3, 0)),
            ('Move Piece', (-2, 1), (1, 4)),
            ('Move Piece', (-1, 3), (-1, 1)),
            ('Move Piece', (3, 1), (4, 0)),
            ('Move Piece', (-1, 1), (-3, -1)),
            ('Move Piece', (-1, 2), (1, 5)),
            ('Move Piece', (-3, -1), (-3, -2)),
            ('Move Piece', (2, 2), (0, 0)),
            ('Move Piece', (-3, -2), (2, 4)),
            ('Move Piece', (4, 0), (-1, -4)),
            ('Move Piece', (2, 4), (-1, 0)),
            ('Move Piece', (-1, -1), (-1, 0)),
            ('Move Piece', (3, 0), (-1, 1)),
            ('Move Piece', (-1, -4), (0, 5)),
            ('Move Piece', (-1, 1), (2, 6)),
            ('Move Piece', (0, 5), (-2, -2)),
            ('Move Piece', (2, 6), (-1, -4)),
            ('Move Piece', (1, -1), (0, -4)),
            ('Move Piece', (1, 1), (0, 0)),
            ('Move Piece', (-1, -3), (2, 2)),
            ('Move Piece', (3, 2), (0, 2)),
            ('Move Piece', (2, 2), (2, 4)),
            ('Move Piece', (1, 3), (2, 4)),
            ('Move Piece', (0, -4), (1, -1)),
            ('Move Piece', (2, 0), (1, -3)),
            ('Move Piece', (-1, 0), (0, 1)),
            ('Move Piece', (-1, -4), (2, -2)),
            ('Move Piece', (1, -1), (2, 0)),
            ('Move Piece', (2, 4), (2, 3)),
            ('Move Piece', (2, 4), (2, 2)),
            ('Move Piece', (2, -2), (1, -4)),
            ('Move Piece', (1, 5), (3, 4)),
            ('Move Piece', (1, -4), (4, 4)),
            ('Move Piece', (2, 2), (3, 2)),
            ('Move Piece', (0, 0), (0, -1)),
            ('Move Piece', (-2, -2), (3, 1)),
            ('Move Piece', (4, 4), (4, 3)),
            ('Move Piece', (-2, -1), (4, 5)),
            ('Move Piece', (-1, 0), (2, 5)),
            ('Move Piece', (0, 1), (-1, 1)),
            ('Move Piece', (2, 5), (1, -2)),
            ('Move Piece', (3, 1), (5, 5)),
            ('Move Piece', (1, -2), (3, 1)),
            ('Move Piece', (5, 5), (-1, 3)),
            ('Move Piece', (4, 3), (-1, 4)),
            ('Move Piece', (1, 4), (3, 3)),
            ('Move Piece', (3, 1), (-1, 2)),
            ('Move Piece', (3, 3), (-1, -4)),
            ('Move Piece', (-1, 2), (2, -2)),
            ('Move Piece', (3, 2), (-2, 3)),
            ('Move Piece', (-1, 4), (-2, -3)),
            ('Move Piece', (-2, 3), (5, 5)),
            ('Move Piece', (-2, -3), (1, -1)),
            ('Move Piece', (-1, -4), (3, 2)),
            ('Move Piece', (2, -2), (4, 6)),
            ('Move Piece', (5, 5), (2, -1)),
            ('Move Piece', (0, -1), (-1, -2)),
            ('Move Piece', (-1, 3), (-2, -3)),
            ('Move Piece', (4, 6), (2, -3)),
            ('Move Piece', (-2, -3), (3, 5)),
            ('Move Piece', (2, -3), (3, 1)),
            ('Move Piece', (3, 2), (3, 6)),
            ('Move Piece', (3, 1), (-1, 3)),
            ('Move Piece', (-1, 1), (-1, 0)),
            ('Move Piece', (-1, 3), (5, 6)),
            ('Move Piece', (3, 6), (0, 4)),
            ('Move Piece', (5, 6), (-1, -1)),
            ('Move Piece', (2, -1), (1, -2)),
            ('Move Piece', (1, 1), (-1, 1)),
            ('Move Piece', (3, 5), (-2, -1)),
            ('Move Piece', (-1, 1), (1, 1)),
            ('Move Piece', (-1, 0), (0, 0)),
            ('Move Piece', (-1, -2), (0, -1)),
            ('Move Piece', (0, 4), (2, 2)),
            ('Move Piece', (0, -1), (0, 0)),
            ('Move Piece', (-2, -1), (-1, 0)),
            ('Move Piece', (-1, -1), (2, -1)),
            ('Move Piece', (-1, 0), (1, 4)),
            ('Move Piece', (2, -1), (4, 4)),
            ('Move Piece', (4, 5), (4, 3)),
            ('Move Piece', (0, 1), (-1, 1)),  # Works correctly up through here
            ('Move Piece', (2, 2), (-1, 0)),
            ('Move Piece', (0, 0), (-1, -1)),
            ('Move Piece', (-1, 0), (3, 0)),
            ('Move Piece', (-1, -1), (-1, 0)),
            ('Move Piece', (1, -2), (-1, -3)),
            ('Move Piece', (-1, 0), (0, 1)),  # Was checking here
            ('Move Piece', (3, 0), (-2, -4)),
            ('Move Piece', (0, 1), (-1, 0)),
            ('Move Piece', (0, 0), (-1, -1)),
            ('Move Piece', (1, -1), (-1, 3)),
            ('Move Piece', (1, 4), (-2, 3)),
            ('Move Piece', (-1, 1), (-2, 0)),
            ('Move Piece', (-2, -4), (-3, 2)),
            ('Move Piece', (-2, 0), (-1, 1)),
            ('Move Piece', (-1, -3), (2, 2)),
            ('Move Piece', (-1, 0), (0, 0)),
            ('Move Piece', (-3, 2), (1, 0)),
            ('Move Piece', (1, -3), (2, -1)),
            ('Move Piece', (2, 2), (2, 4)),
            ('Move Piece', (2, -1), (3, 2)),
            ('Move Piece', (3, 4), (1, 4)),
            ('Move Piece', (4, 4), (1, -1)),
            ('Move Piece', (-2, 3), (-1, -3)),
            ('Move Piece', (-1, 3), (-2, -2)),
            ('Move Piece', (2, 4), (4, 2)),
            ('Move Piece', (2, 3), (1, 3)),
            ('Move Piece', (4, 2), (-1, 0)),
            ('Move Piece', (0, 0), (0, -1)),
            ('Move Piece', (-1, -3), (2, 5)),
            ('Move Piece', (1, 2), (5, 3)),
            ('Move Piece', (0, 0), (-2, 0)),
        ]
        self._test_game_helper(actions)


if __name__ == '__main__':
    unittest.main()
