default:
    image: python:latest
    before_script:
        - |
            export PATH="/home/gitlab-runner/.pyenv/bin:$PATH"
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"

stages:
    - test
test:
    script:
        - |   
            uname -a
            pyenv install -l
            pyenv install 3.10.4
            pyenv versions
            pyenv global 3.10.4
            pyenv prefix
            python -V
            
            whoami
            pwd
            python3 --version
            coverage run -m unittest test/test_*.py
            coverage report -m
