default:
    image: python:3.10
before_script:
    - apt-get install python3-dev
    - python3 --version
stages:
    - test
test:
    script:
        - coverage run -m unittest test/test_*.py
        - coverage report -m