default:
    image: python:latest
    before_script:
        - |
stages:
    - test
test:
    script:
        - |   
            coverage run -m unittest test/test_*.py
            coverage report -m

#export PATH="/home/gitlab-runner/.pyenv/bin:$PATH"
#            eval "$(pyenv init -)"
#            eval "$(pyenv virtualenv-init -)"

#uname -a
#            ls -ls /usr/bin/python*
#
#            whoami
#            pwd
#            python3 --version
#pyenv install -l
#            pyenv install anaconda3:latest
#            pyenv versions
#            pyenv global anaconda3:latest
#            pyenv prefix
#            python -V