default:
    image: python:3.10
stages:
    - test
test:
    script:
        - coverage run -m unittest test/test_init_*.py
        - coverage run -m unittest test/test_sample_*.py
        - coverage report -m