default:
    image: python:3.8
    before_script:
       - apt-get update
       - apt-get install -y python3-pip
       - pip install -r requirements.txt
stages:
    - test
test:
    script:
        - coverage run -m unittest test/test_*.py
        - coverage report