default:
    image: python:latest
stages:
    - test
test:
    image: python:latest
    script:
        - whoami
        - which python3.10
        - python3 --version
        - coverage run -m unittest test/test_*.py
        - coverage report -m